[workspace]
resolver = "2"
members = [
    "behavior",
    "behavior-macros",
    "behavior-util",

    # Internalo
    "benches",
    "examples",
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
