[package]
name = "behavior-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["visit"] }
quote = "1.0"
proc-macro2 = "1.0"
serde = { version = "*", feature = "derive, serde_derive" }
serde_json = { version = "*" }
